---
- name: Build and Push Docker Image
  hosts: jenkins
  vars:
    image_name: ayushrobets/springapp
    image_tag: latest
    docker_user: "{{ lookup('env','DOCKER_USER') }}"
    docker_pass: "{{ lookup('env','DOCKERHUB_TOKEN') }}"

  tasks:
    - name: Login to Docker Hub
      shell: |
        echo "{{ docker_pass }}" | docker login -u "{{ docker_user }}" --password-stdin

    - name: Build Docker image
      shell: |
        docker build -t {{ image_name }}:{{ image_tag }} .

    - name: Push Docker image
      shell: |
        docker push {{ image_name }}:{{ image_tag }}
